webappold/config/routes.rb
Webapp::Application.routes.draw do

  match '/first/login' => 'first#login', :as => :first_login 
  match '/first/logout' => 'first#logout', :as => :first_logout 
  match '/users/search' => 'users#search', :as => :users_search 
	
	resources :projects do 
	 resources :minigoals
	end
	resources :users
	resources :first
	resources :minigoals
	
  

  root :to => 'first#index'

end

webappold/app/models/minigoal.rb
class Minigoal < ActiveRecord::Base
	belongs_to :project
	has_one :status
	belongs_to :status
	
	validates :name, 
			  :presence => {:message => ": Field seems to be missing"}
			  
end

webappold/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :minigoals
	has_and_belongs_to_many :users
	
	validates :name, 
			  :presence => {:message => ": Field seems to be missing"},
			  :length => {:minimum => 5, :message => ": Must be longer than 4 characters"}
	validates :name, :uniqueness => true
	
	validates :description, 
			  :presence => {:message => ": Field seems to be missing"},
			   :length => {:maximum => 250, :message => ": Field can not be longer than 250 characters"}
			 
			  
end

webappold/app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :projects
	
	validates :first_name, 
			  :presence => {:message => "First name seems to be missing"},
			  :length => {:maximum => 20, :message => "First name of the user can not be longer than 20 characters"}
			  
			  
	validates :last_name, 
			  :presence => {:message => "Last name seems to be missing"},
			  :length => {:maximum => 40, :message => "Last name of the user can not be longer than 20 characters"}
			  
	validates :email, 
			  :presence => {:message => "Email seems to be missing"}
			  
	validates :email, :uniqueness => true		  
			  
	validates :email,  :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, :message =>"Invalid email"}
	
	validates :password, 
			  :presence => {:message => "Password seems to be missing"},
			  :length => {:minimum => 5, :maximum => 30, :message => "Password must be at least 5 and maximum 30 characters"}
			  #Get a maximum length for password to!
			  
	
end

webappold/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

webappold/app/controllers/first_controller.rb
class FirstController < ApplicationController
	def index
		@sessionLogin = session[:loggedIn]
		@sessionId = session[:userId]
	end
	
	def login
		
		@email = params[:email]
		@password = params[:password]
		@user = User.where("email = ? AND password = ?", @email, @password)
		
		
		if @user.size > 0 
			@something = @user.first.id
			@firstName = @user.first.first_name
			session[:userId] = @something
			session[:loggedIn] = true
			
			@sessionLogin = session[:loggedIn]
			@sessionId = session[:userId]	
		else 		
			redirect_to(:action => 'index')
			
		end
		
	end
	
	def logout
		#session id deleted here
		session[:userId] = nil
		session[:loggedIn] = false
		redirect_to(:action => 'index')
		
	end
	
	def test
	
	end
	
end

webappold/app/controllers/minigoals_controller.rb
class MinigoalsController < ApplicationController

	def index
		if session[:loggedIn] == true	
			@minigoals = Minigoal.all		
		else 
			flash[:notice] = "You are not logged in"
		end
	end
	
	def show
		if session[:loggedIn] == true	
			@minigoal = Minigoal.find(params[:id])
			@minigoalProject = @minigoal.project_id
			@projectName = Project.find_by_id(@minigoalProject)
			@minigoalStatus = @minigoal.status_id 
			@status = Status.find_by_id(@minigoalStatus)
			
		else 
			flash[:notice] = "You are not logged in"
		end
	end
	
	def new
		#Here I want access to the project that should contain the minigoal. 
		if session[:loggedIn] == true	
			@minigoal = Minigoal.new
		else 
			flash[:notice] = "You are not logged in"
		end
	end
	
	def create
	    
		@minigoal = Minigoal.new(params[:minigoal])
		if @minigoal.save
			redirect_to minigoals_path			
		else
		render :action => "new"
		end
		
	end
	
	def destroy
		@minigoal = Minigoal.find(params[:id])
		@minigoal.destroy
		redirect_to minigoals_path
	end
	
	def edit
		if session[:loggedIn] == true	
			@minigoal = Minigoal.find(params[:id])	
		else 
			flash[:notice] = "You are not logged in"
		end
	end
	
	def update
		@minigoal = Minigoal.find(params[:id])	
		if @minigoal.update_attributes(params[:minigoal])
			redirect_to minigoals_path
		else
			render :action => "edit"
		end
	end

end

webappold/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		if session[:loggedIn] == true
			@users = User.all 
			
		else 
			flash[:notice] = "You are not logged in"
		end
	end
	
	def new		
		
			@user = User.new	
		
	end
	
	def show 
	    if session[:loggedIn] == true			
			user = User.where("id = ?", params[:id])
			@sessionId = session[:userId] 
			@userId = user.first.id	
			if !user.empty?
				@userfname = user.first.first_name
				@userlname = user.first.last_name
				@email = user.first.email
				@uprojects = user.first.projects
			else
				flash[:notice] = "This user does not exist"
			end
		else 
			flash[:notice] = "You are not logged in"
		end
		
	end
	
	
	def search
		if session[:loggedIn] == true
			@searchPhrase =  params[:search]
			#stolen from google, matches everything that has the search phrase in it
			@users= User.find(:all, :conditions=> ["first_name like :eq", {:eq => "%" + @searchPhrase + "%"}])		
			@size = @users.size 
			@first = @users.first.first_name
		else 
			flash[:notice] = "You are not logged in"
		end			
	end
	
	def create	    
		@user = User.new(params[:user]) 
		if @user.save
			redirect_to root_url
		else
			render :action => "new"
		end
		
	end
	
	def update
		@user = User.find(params[:id])	
		if @user.update_attributes(params[:user])
			redirect_to users_path
		else
			render :action => "edit"
		end
	end
	
	def edit
		if session[:loggedIn] == true	
			@sessionId = session[:userId] 
			@user = User.find(params[:id])
			@userId = @user.id	
		else 
			flash[:notice] = "You are not logged in"
		end	
	end
	
	def destroy
		@sessionId = session[:userId] 
		@user = User.find(params[:id])
		@userId = @user.id
		if (@userId == @sessionId)
			@user.destroy
		end
		redirect_to first_logout_path
	end
	
end

webappold/app/views/first/index.html.erb
<div class="container">
<div class="Title"><h1>Steffos Ruby application</h1></div>
<!--<%= link_to "Create new user", new_user_path %>-->


<!--<%= link_to "Go to the users page", users_path %>-->
<br>
<%= form_tag(first_login_path :method => "post", :action => "login", :class => "myForm") do%>
<!-- Access to action in form_tag check it. -->

	<%= label_tag(:email, "Email:") %>
	<%= text_field_tag(:email) %>
	
	<%= label_tag(:password, "Password:") %>
	<%= text_field_tag(:password) %>

	<%= submit_tag("Login") %>
	
<% end %>

<%= @sessionLogin %>
<%= @sessionId %>
		

<div id="notauser">
<p>Not a user?  <%= link_to "Sign up here", new_user_path %><p>
</div>

<div class="footer">
<p>@steffo 2013<p>
</div>
</div>

webappold/app/views/first/login.html.erb
<div class="container">
	<div class="Title">
		<h1>Welcome! <%= @firstName%> </h1>
	</div>

	<%= link_to "Go to users page", users_path %>
	<!--  Should go to the users own page instead -->
	<br>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
</div>

webappold/app/views/minigoals/edit.html.erb
<div class="container">
	<div class="Title">
		<h1>Edit minigoal</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>	
	
	<h3><%= @minigoal.name %></h3>
	

	<%= form_for @minigoal do |f| %>
		 		
		<div class="text_field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="select_box">
			<%= f.label :status_id %>
			<%= f.select :status_id, options_from_collection_for_select(Status.all, :id, :name) %>	
		</div>
		
		<div class="submit">
			<%= f.submit "Save changes" %>
		</div>
	<br>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<br>
	<p><%= link_to "Back to Minigoals", minigoals_path(@minigoal) %></p>
	
	<% end %>
	<% end %>
	
	<!-- Change this one so you can see the status instead -->
	
</div>

webappold/app/views/minigoals/index.html.erb
<div class="container">
	<div class="Title">
		<h1>Minigoals for this project</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>	
	<table>
		<% @minigoals.each do |minigoal| %>
			<tr>
				<td><%= link_to minigoal.name, minigoal %></td>
				<td><%= link_to "Edit", edit_minigoal_path(minigoal) %></td>	
				<td><%= link_to "Delete", minigoal, confirm: "You're about to delete this minigoal", method: :delete%></td>
			</tr>	
		<% end %>
	<table>
	<br>

	<%= link_to "Create new minigoal", new_minigoal_path %>
	<br>
	<%= link_to "Go to the all projects page", projects_path %>
	<br>
	<%= link_to "Go to the all users page", users_path %>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
<div>

webappold/app/views/minigoals/new.html.erb
<div class="container">
	<div class="Title">
		<h1> This is where you create a new minigoal </h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>	
	<% if @minigoal.errors.any? %>
		<div id="error_messages">
		
		<ul class = "errorlist">
		<% @minigoal.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
		</div>
	<% end %>	

	<%= form_for @minigoal do |f| %>
	<!-- Should maybe be a drop down list instead -->
		
	
		<div class="text_field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		
		<div class="select_box">
			<%= f.label :status_id %>
			<%= f.select :status_id, options_from_collection_for_select(Status.all, :id, :name) %>	
		</div>
		
		<div class="submit">
			<%= f.submit "Create minigoal" %>
		</div>
	<br>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
	<% end %>
	<!-- Might be a good idea to put in status in a select box-->
</div>

webappold/app/views/minigoals/show.html.erb
<div class="container">
	<div class="Title">
		<h1> Specific minigoal page </h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>	
	<p>Name: <%= @minigoal.name %>
	<p>Belongs to the project: <%= @projectName.name %></p>
	<p>Has the status: <%= @status.name %></p>
	<p><%= link_to "Edit this minigoal", edit_minigoal_path %></p>
	<p><%= link_to "Delete this minigoal", @minigoal, confirm: "You're about to delete this minigoal", method: :delete%></p>
	<br>
	<%= link_to "Go to the all projects page", projects_path %>
	<br>
	<%= link_to "Go to the all users page", users_path %>
	<br>
	<%= link_to "Back to this projects page", project_path(@projectName) %>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>	
</div>

webappold/app/views/users/edit.html.erb
<div class="container">
	<div class="Title">
		<h1>Edit member</h1>
	</div>
	<% if flash[:notice] %>
			<h2 class="error"><%= flash[:notice] %></h2>
			<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>

	<%= link_to "Back to users", user_path(@user) %>
	<p>SessionId: <%= @sessionId %></p>
	<p>UserId: <%= @userId %></p>
	<% if @sessionId != @userId %>
		<p>You do not have authority to edit this page!</p>
	<% else %>	
	
		<%= form_for @user do |f| %>
			<div class="text_field">
				<%= f.label :first_name %>
				<%= f.text_field :first_name %>
			</div>
			<div class="text_field">
				<%= f.label :last_name %>
				<%= f.text_field :last_name %>
			</div>
			<div class="text_field">
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>
			<div class="text_field">
				<%= f.label :password %>
				<%= f.text_field :password %>
			</div>
			<div class="submit">
				<%= f.submit "Save changes" %>
			</div>
		
		<% end %>
		<% end %>
		
		<br>
		<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<!-- Access to action in form_tag check it. -->
			<%= submit_tag("Logout") %>
		<% end %>
	<% end %>
</div>
<!-- Form goes here -->

webappold/app/views/users/index.html.erb
<div class="container">
	<div class="Title">
		<h1>All users</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>
	
	<!-- Link to create new user and to create new project-->
	<!-- Cant get to the create_users_path controller -->
	<!--<%= link_to "Create new user", new_user_path %>-->
	<br>
	<div class="users">
	<br>
	<table>
		<% @users.each do |user| %>
			<tr>
			<td><%= link_to user.first_name, user %></td>
			<td><%= link_to "Edit user", edit_user_path(user) %></td>
			<tr>	
		<%end %>
	</table>
	</div>
	<br>
	<%= link_to "Go to the projects page", projects_path %>
	<br>
	<!-- This link leeds to the wrong place -->
	
	<br>
	<br>
	<br>
	<div class="searchForm">
		<%= form_tag(users_search_path :method => "post", :action => "search", :class => "searchForm") do%>
		<!-- Access to action in form_tag check it. -->
			<h3> Search among the users of this application </h3>
			<%= label_tag(:search, "Search:") %>
			<%= text_field_tag(:search) %>			
			<%= submit_tag("Search") %>		
		<% end %>
	</div>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
	<!-- Access to action in form_tag check it. -->
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
</div>

webappold/app/views/users/new.html.erb
<div class="container">
	<div class="Title">		
		<h1>Create User</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>
	
	<!-- See if this one is applicable to other types of errors-->
	<% if @user.errors.any? %>
		<div id="error_messages">
		
		<ul class = "errorlist">
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
		</div>
	<% end %>	


	<%= form_for @user do |f| %>
		<div class="text_field">
			<%= f.label :first_name %>
			<%= f.text_field :first_name %>
		</div>
		<div class="text_field">
			<%= f.label :last_name %>
			<%= f.text_field :last_name %>
		</div>
		<div class="text_field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div class="text_field">
			<%= f.label :password %>
			<%= f.text_field :password %>
		</div>
		<div class="submit">
			<%= f.submit "create user" %>
		</div>
		
	<% end %>

	<p><%= link_to "Back to log in page! ", first_logout_path %></p>
	<% end %>

	
</div>

webappold/app/views/users/search.html.erb
<div class="container">
	<div class="Title">
		<h1>The results of your search</h1>
	</div>
	<h3> Your search phrase was:<%= @searchPhrase %> </h3>
	<p> Here are your search results </p>

	<!--<%= @size %>-->
	
	<table>
		<% @users.each do |user| %>
			<tr>
				<td><%= link_to user.first_name, user %></td>	
				<!-- <td><%= link_to "Edit user", edit_user_path(user) %></td> -->
			</tr>
		<%end %>		
	<table>
	</div>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
	<!-- Access to action in form_tag check it. -->
		<%= submit_tag("Logout") %>
	<% end %>
	<br>
</div>

webappold/app/views/users/show.html.erb
<div class ="container">
	<div class="Title">
		<h1>Information about the user</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>
	<% else %>
		<p>Session Id: <%= @sessionId %></p>
		<p>User Id: <%= @userId %></p>
	
		<p>First Name of the user is: <%= @userfname %></p>
		<p>Last Name of the user is: <%= @userlname %></p>
		<p>Email of the user is: <%= @email %></p>		


	<h3>Projects made by this user</h3>
	<% if @uprojects.size < 1 %>
		<p> This user does not have any projects yet </p>
	<% end %>
	<% @uprojects.each do |uproject| %>
		<%= link_to uproject.name, project_path(uproject) %> <br>
	<% end %>
	
	<br>
	
	<p><%= link_to "Back to the All users page", users_path %></p>
	
	<% if @sessionId == @userId %>
		<p><%= link_to "Delete yourself", @user, confirm: "You're about to delete yourself", method: :delete%></p>
	<% end %>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
	<!-- Access to action in form_tag check it. -->
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
</div>