johnfiler/webapp/webapp/config/routes.rb
Webapp::Application.routes.draw do
  get "errors/error_404"

  get "errors/error_500"

  match '/first/login' => 'first#login', :as => :first_login 
  match '/first/logout' => 'first#logout', :as => :first_logout 
  match '/users/search' => 'users#search', :as => :users_search 
  match '/projects/userchange' => 'projects#userchange', :as => :projects_userchange
	
	resources :projects do 
	 resources :minigoals
	end
	resources :users
	resources :first
	resources :minigoals
	
	
  

  root :to => 'first#index'

end

johnfiler/webapp/webapp/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :minigoals
	has_and_belongs_to_many :users
	
	validates :name, 
			  :presence => {:message => ": Field seems to be missing"},
			  :length => {:minimum => 5, :message => ": Must be longer than 4 characters"}
	validates :name, :uniqueness => true
	
	validates :description, 
			  :presence => {:message => ": Field seems to be missing"},
			  :length => {:maximum => 250, :message => ": Field can not be longer than 250 characters"}
			  
	validates :start, 
			  :presence => {:message => ": You must fill in the start date right"}
			  
	validates :end, 
			  :presence => {:message => ": You must fill in the end date right"}
			 
			  
end

johnfiler/webapp/webapp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	#before_filter :check_id, :only => :edit
	before_filter :check_id, :only => [:edit, :delete]
	
	def index
		if session[:loggedIn] == true						
			@projects = Project.all
		else 
			flash[:notice] = "You are not logged in"
		end
	end

	def show 
		if session[:loggedIn] == true	
			@validUser = false
			@userId = session[:userId]
			@project = Project.find(params[:id])
			#@projectUserId = @project.owner_id
			@prownerId = @project.owner_id
			@prowner = User.find(@prownerId)

			if @prownerId == @userId
				@validUser = true
			end

			@prusers = @project.users

			@prusers.each do |pruser|	
			@validPruser = pruser
				if pruser.id == @userId
					@validUser = true
				end
			end 



			@pMinigoals = @project.minigoals
			@projectName = @project.name
			@projectDescription = @project.description



		else 
			flash[:notice] = "You are not logged in"
		end
	end

	def create

		#flash[:notice] = params

		@project = Project.new(params[:project])
		@userId = session[:userId]
		@user = User.find(@userId)
		@project.owner_id = @userId

		User.all.each do |u|
			flash[:notice] = params[u.id]
			if  params[u.id.to_s]
				@pruser = User.find(u.id)
				@project.users << @pruser

			end
		end

		@project.users << @user	
		if @project.save
			redirect_to projects_path
		else 
			render :action => "new"
		end
	end

	def destroy
	#before-filter should be here
		#before_filter :check_id
		@sessionId = session[:userId]
		@project = Project.find(params[:id])
		@projectUserId = @project.owner_id
		if @projectUserId == @sessionId 
			@crap = Project.find(params[:id])
			@crap.destroy
			redirect_to projects_url
		end
	end

	def new
		if session[:loggedIn] == true
		@users = User.all
		@nrusers = @users.size
		@userSize = @users.size
		@userId = session[:userId]
			@project = Project.new
		else 
				flash[:notice] = "You are not logged in"
		end
	end

	def edit
		if session[:loggedIn] == true	
			#flash[:notice] = "hejsan"
			@sessionId = session[:userId]
			@validUser = false
			@project = Project.find(params[:id])
			@sessionId = session[:userId]
			@projectUserId = @project.owner_id
			@prowner = User.find(@project.owner_id)				

			if @prowner.id == @sessionId
				@validUser = true
			end
			@prusers = @project.users
			#@validUser = false
			@prusers.each do |pruser|	
			@checkedUser = pruser
			
				if pruser.id == @sessionId
					
					@validUser = true
				end
			end 
			
			@checkedUsers = @project.users
			@checkedUsers.all.each do |checkedUser|
				@ckUser = checkedUser
			end 
			


		else 
			flash[:notice] = "You are not logged in"
		end
	end	

	def update

		@userId = session[:userId]
		@project = Project.find(params[:id])
		@user = User.find(@userId)

		User.all.each do |u|

				@pruser = User.find(u.id)
				@project.users.delete(@pruser)
				#flash[:notice] = params[u.id]
				if  params[u.id.to_s]
					#flash[:notice] = "testing"
					#@project.users.delete(@pruser)
					@project.users << @pruser

				end
			end
		@project.users << @user	
		if @project.update_attributes(params[:project])
			redirect_to projects_path
		else
			render :action => "edit"
		end
	end

	def userchange
		#lite kod

		@project = Project.find(params[:id])

		params[:User]

		if @project.update_attributes(params[:project])
			redirect_to projects_path
		else
			render :action => "edit"
		end
	end
	
	def check_id
		@userId = session[:userId]
		@project = Project.find(params[:id])
		@projectOwner= @project.owner_id
		
		if @userId != @projectOwner
			redirect_to project_path
		end
	end
end

johnfiler/webapp/webapp/app/helpers/projects_helper.rb
module ProjectsHelper
end

johnfiler/webapp/webapp/app/views/projects/edit.html.erb
<div class = "container">
	<div class = "Title">
		<h1>The edit page</h1>
	</div>
	<% @sessionId %>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>



	<br>
	

	<% if @validUser == true %>
		<%= form_for @project do |f| %>

			<div class="text_field">
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>
			<div class="text_area">
				<%= f.label :description %>
				<%= f.text_area :description %>
			</div>
			<div class="text_field">
				<%= f.label :start %>
				<%= f.text_field :start %>
			</div>

			<div class="text_field">
				<%= f.label :end %>
				<%= f.text_field :end %>
			</div>

			<h3> Choose who you want to have authority to this project </h3>
			
			<% User.all.each do |u| %>	
			
				<!--<% @prusers.each do |pruser| %>
						<%if pruser.id == u.id%>
							<%= pruser.first_name %>
							
						<% end %>
					<% end %>-->
			
				<!--<% if @prusers.include?(u)%>
				   <%= check_box_tag u.id, 1, true %>
				<% end %>-->
			
				<%if @sessionId == u.id %>
					<div class="invisible">
						<%= label_tag u.first_name %>
						<%= check_box_tag u.id %> <br>
					</div>
				<% else %>
					<% if @prusers.include?(u)%>
						<%= label_tag u.first_name %>
						<%= check_box_tag u.id, 1, true %>
					<% else %>
						<%= label_tag u.first_name %>
						<%= check_box_tag u.id %> <br>
					<% end %>
				<% end %>
			
				<!-- <%= check_box_tag u.id, 1, true %> <br> -->
			<% end %>
			<br>


			<!-- Should be a select box here where you can chose the minigoal_id -->
			<div class="submit">
				<%= f.submit "Save changes" %>
			</div>		
		<% end %>
	<% else %>
	<p class="error"> You should not be here you naughty boy!!!</p>
	<% end %>

	<%= link_to "Back to projects", projects_path %>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
	<div class="footer">
		<p>@steffo 2013<p>
	</div>
</div>

johnfiler/webapp/webapp/app/views/projects/index.html.erb
<div class="container
<div class="sizeHelper2">
	<div class="Title">
		<h1>All projects </h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>	
	<h3> The following projects exist right now</h3>
	<div class="projects_links">	
		<table>
			<% @projects.each do |project| %>
			<tr>
			<!--Try to get a link to the projects user within the table as well-->	
				<td><%= link_to project.name, project %></td>
				<!--<td><%= link_to "Edit project", edit_project_path(project) %></td>-->
			</tr>	
			<%end %>
		</table>
	</div>
	<br>
	<%= link_to "Create new project", new_project_path %>
	<br>
	<%= link_to "Back to the users page", users_path %>


	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
	<!-- Access to action in form_tag check it. -->
		<%= submit_tag("Logout") %>
	<%end %>
	<% end %>
	</div>
	<div class="footer">
		<p>@steffo 2013<p>
	</div>
</div>

johnfiler/webapp/webapp/app/views/projects/new.html.erb
<div class="container">
	<div class="Title">
		<h1>Create Project</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%=h flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>

	<% if @project.errors.any? %>
		<div id="error_messages">

		<ul class = "errorlist">
		<% @project.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
		</div>
	<% end %>	<% @userId %>

	<%= form_for @project do |f| %>
		<div class="text_field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="text_area">
			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>
		<div class="text_field">

			<%= f.label :start %> <p> YYYY-MM-DD </p>
			<%= f.text_field :start %>
		</div>	

		<div class="text_field">
			<%= f.label :end %> <p> YYYY-MM-DD </p>
			<%= f.text_field :end %>
		</div>

		<h3> Choose who you want to have authority to this project </h3>
		<% User.all.each do |u| %>
			<%if @userId == u.id %>
				<div class="invisible">
					<%= label_tag u.first_name %>
					<%= check_box_tag u.id %> <br>
				</div>
			<% else %>
				<%= label_tag u.first_name %>
				<%= check_box_tag u.id %> <br>
			<% end %>
		<% end %>

		<br>
		<div class="submit">
			<%= f.submit "create project" %>
		</div>

	<% end %>

	<p><%=link_to "Back to users", users_path %></p>
	<p><%=link_to "Back to projects", projects_path %></p>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
	<div class="footer">
		<p>steffo 2013</p>
	</div>
</div>

johnfiler/webapp/webapp/app/views/projects/show.html.erb
<div class="container">	
	<div class="Title">
		<h1>Page to show specific Project</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>

	<br>



	<p>Name of the project: <%= @projectName %></p>
	<p>Description of the project: <%= @projectDescription %></p
	<p>Owner of this project: <%= @prowner.first_name %> <%= @prowner.last_name %></p>
	<h3>Users that belongs to this project</h3>
	<% @prusers.all.each do |pruser| %>
		<%= pruser.first_name %>
		<!--<%if pruser == @validPruser %>
			<p>valid</p>
		<% end %>-->
	<% end %>
	
	<!--<% User.all.each do |user| %>
		<%= user.first_name %>
		<p>hej</p>
	<% end %>-->
		




	<div id ="mgBox">
		<h3>The minigoals that the project has:</h3>
		<% if @pMinigoals.size < 1 %>
			<p> Project has no minigoals </p>
		<% end %>
		<table>
			<% @pMinigoals.each do |pminigoal| %>
				<tr>
				<td><%= link_to pminigoal.name, minigoal_path(pminigoal) %></td>
				<!--<td><%= pminigoal.status_id %></td><!-- Change this one to status name-->
				<tr>	
			<%end %>
		</table>
	</div>
	<br>
	<%if @validUser == true %>
		<p><%= link_to "Create Minigoal for project", new_project_minigoal_path(@project) %></p>
	<% end %>
	

	<% if @userId == @project.owner_id %>
		<p><%= link_to "Edit this project", edit_project_path %></p>
		<p><%= link_to "Delete this project", @project, confirm: "You're about to delete this project", method: :delete%></p>
	<% end %>
	<p><%=link_to "Create new project", new_project_path %></p>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
	<!-- Access to action in form_tag check it. -->
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
	<div class="footer">
		<p>@steffo 2013<p>
	</div>
</div>