johnfiler/webapp/webapp/config/routes.rb
Webapp::Application.routes.draw do
  get "errors/error_404"

  get "errors/error_500"

  match '/first/login' => 'first#login', :as => :first_login 
  match '/first/logout' => 'first#logout', :as => :first_logout 
  match '/users/search' => 'users#search', :as => :users_search 
  match '/projects/userchange' => 'projects#userchange', :as => :projects_userchange
	
	resources :projects do 
	 resources :minigoals
	end
	resources :users
	resources :first
	resources :minigoals
	
	
  

  root :to => 'first#index'

end

johnfiler/webapp/webapp/app/models/minigoal.rb
class Minigoal < ActiveRecord::Base
	belongs_to :project
	has_one :status
	belongs_to :status
	belongs_to :user
	
	validates :name, 
			  :presence => {:message => ": Field seems to be missing"}
			  
	validates :name, :uniqueness => true
			  
end

johnfiler/webapp/webapp/app/controllers/minigoals_controller.rb
class MinigoalsController < ApplicationController

	before_filter :check_id, :only => [:edit, :delete]

	def index
		if session[:loggedIn] == true	
			@minigoals = Minigoal.all		
		else 
			flash[:notice] = "You are not logged in"
		end
	end

	def show
		if session[:loggedIn] == true
			@sessionUserId = session[:userId]		
			@currentUser = User.find(@sessionUserId)
			@currentUserId = @currentUser.id
			@minigoal = Minigoal.find(params[:id])
			@minigoalProject = @minigoal.project_id
			@projectName = Project.find_by_id(@minigoalProject)
			@minigoalStatus = @minigoal.status_id 
			@status = Status.find_by_id(@minigoalStatus)
			@mgUserId = @minigoal.user_id
			@mgUser =  User.find_by_id(@mgUserId)

			else 
			flash[:notice] = "You are not logged in"
			end
	end

	def new
		#Here I want access to the project that should contain the minigoal.
		if  session[:loggedIn] == true			
			@project = Project.find(params[:project_id])
			@sessionId = session[:userId]
			@prusers = @project.users
			@validUser = false
			@prusers.each do |pruser|		
				if pruser.id == @sessionId
					@validUser = true
				end
			end 			
				@minigoal = Minigoal.new
		else 
			flash[:notice] = "You are not logged in"
		end
	end

	def create

		@minigoal = Minigoal.new(params[:minigoal])	
		@project = Project.find(params[:project_id])	

		@minigoal.project = @project
		@minigoal.user_id = session[:userId] 
		if @minigoal.save
			redirect_to projects_path			
		else
			render :action => "new"
			@validUser = true
		end

	end

	def destroy
		@sessionId = session[:userId]				
		@minigoal = Minigoal.find(params[:id])
		@minigoalUserId = @minigoal.user_id
		if @sessionId == @minigoalUserId
			@minigoal.destroy
		end
		redirect_to projects_path
	end

	def edit
		if session[:loggedIn] == true	
		@validUser = false
			@sessionId = session[:userId]			
			@minigoal = Minigoal.find(params[:id])	
			@minigoalUserId = @minigoal.user_id
			if @minigoalUserId == @sessionId
				#flash[:notice] = "You do not have authority to edit this minigoal"
				@validUser = true
			end
		else 
			flash[:notice] = "You are not logged in"
		end
	end

	def update
		@minigoal = Minigoal.find(params[:id])	
		if @minigoal.update_attributes(params[:minigoal])
			redirect_to projects_path
		else
			render :action => "edit"
		end
	end
	
	def check_id
		@userId = session[:userId]
		@minigoal = Minigoal.find(params[:id])
		@minigoalUserId = @minigoal.user_id
		
		if @userId != @minigoalUserId
			redirect_to projects_path
		end
	end

end

johnfiler/webapp/webapp/app/helpers/minigoals_helper.rb
module MinigoalsHelper
end

johnfiler/webapp/webapp/app/views/minigoals/edit.html.erb
<div class="container">
	<div class="Title">
		<h1>Edit minigoal</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to users page |", users_path %><%= link_to "  Back to Minigoals", minigoals_path %>		
	<% else %>	
	
	<% if @validUser == true %>
		<h3><%= @minigoal.name %></h3>
		

		<%= form_for @minigoal do |f| %>

			<div class="text_field">
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>

			<div class="select_box">
				<%= f.label :status_id %>
				<%= f.select :status_id, options_from_collection_for_select(Status.all, :id, :name) %>	
			</div>

			<div class="submit">
				<%= f.submit "Save changes" %>
			</div>
		<% end %>
		<br>
		<br>
		<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
			<%= submit_tag("Logout") %>
		<% end %>
		<br>
		<p><%= link_to "Back to Projects", minigoals_path(@minigoal) %></p>
		
	<% else %>
		<p class="error">Get out of here!!!</p>
		<br>
		<%= link_to "Go to the all users page", users_path %>
		<br>
		<%= link_to "Back to the projects page", projects_path %>
	<% end %>
	<% end %>
	<br>
	<br>
	<%= submit_tag("Logout") %>

	<div class="footer">
		<p>@steffo 2013<p>
	</div>
	<!-- Change this one so you can see the status instead -->

</div>

johnfiler/webapp/webapp/app/views/minigoals/index.html.erb
<div class="container">
	<div class="Title">
		<h1>All of the minigoals</h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>	
	<h3> The following minigoals have been created </h3>
	<div class="users_links">
	<table>
		<% @minigoals.each do |minigoal| %>
			<tr>
				<td><%= link_to minigoal.name, minigoal %></td>
				<!--<td><%= link_to "Edit", edit_minigoal_path(minigoal) %></td>	-->
				<!--<td><%= link_to "Delete", minigoal, confirm: "You're about to delete this minigoal", method: :delete%></td>-->
			</tr>	
		<% end %>
	</table>
	</div>
	<br>

	<!--<%= link_to "Create new minigoal", new_minigoal_path %>-->
	<br>
	<%= link_to "Go to the all projects page", projects_path %>
	<br>
	<%= link_to "Go to the all users page", users_path %>
	<br>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
	<br>
	<div class="footer">
		<p>@steffo 2013<p>
	</div>
<div>

johnfiler/webapp/webapp/app/views/minigoals/new.html.erb
<div class="container">
	<div class="sizeHelper">
		<div class="Title">
			<h1> This is where you create a new minigoal </h1>
		</div>
		<% if flash[:notice] %>
			<h2 class="error"><%= flash[:notice] %></h2>
			<%= link_to "Back to log in page! ", first_logout_path %>		
		<% else %>	
		<% if @minigoal.errors.any? %>
			<div id="error_messages">

			<ul class = "errorlist">
			<% @minigoal.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
			</div>
		<% end %>	
		<!--<%= @project.id %>-->
		
		<br>
		<br>
		<% if @validUser == true %>
			<%= form_for([@project, @minigoal]) do |f| %>
				<!--<div class="allowedMembers">
					<h3>The following members have authority to create this minigoal</h3>
					<% @prusers.each do |pruser| %>
						<p><%=pruser.first_name %>	<%=pruser.last_name %></p>
					<%end %>
				</div>-->
				<div class="text_field">
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>

				<!--<div class="text_field">
					<%= f.label :start %> <p>(YYYY-MM-DD)</p>
					<%= f.text_field :start %>
				</div>
				
				<div class="text_field">
					<%= f.label :end %> <p>(YYYY-MM-DD</p>
					<%= f.text_field :end %>
				</div>-->

				<div class="select_box">
					<%= f.label :status_id %>
					<%= f.select :status_id, options_from_collection_for_select(Status.all, :id, :name) %>	
				</div>

				<div class="submit">
					<%= f.submit "Create minigoal" %>
				</div>


			<% end %>


			<br>

			<br>
			<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
				<%= submit_tag("Logout") %>
			<% end %>
		<% else %>
			<p class="error">You should not be here you naughty boy!!!</p>
		<% end %>
		<br>
		<%= link_to "Go to the all users page", users_path %>
		<% end %>

		<!-- Might be a good idea to put in status in a select box-->		
	</div>
	<div class="footer">
			<p>@steffo 2013<p>
	</div>
</div>

johnfiler/webapp/webapp/app/views/minigoals/show.html.erb
<div class="container">
	<div class="Title">
		<h1> Specific minigoal page </h1>
	</div>
	<% if flash[:notice] %>
		<h2 class="error"><%= flash[:notice] %></h2>
		<%= link_to "Back to log in page! ", first_logout_path %>		
	<% else %>	


	
	
	<p>This minigoal belongs to the project: <%= @projectName.name %></p>
	<p>Name of the minigoal: <%= @minigoal.name %>
	<p>Has the status: <%= @status.name %></p>


	<p>The owner of this minigoal is: <%= @mgUser.first_name %> <%= @mgUser.last_name %></p>
	<% if @mgUserId == @sessionUserId %>
		<p><%= link_to "Edit this minigoal", edit_minigoal_path %></p>
		<p><%= link_to "Delete this minigoal", @minigoal, confirm: "You're about to delete this minigoal", method: :delete%></p>
	<%end %>
	<br>
	<%= link_to "Go to the all projects page", projects_path %>
	<br>
	<%= link_to "Go to the all users page", users_path %>
	<br>
	<%= link_to "Back to this projects page", project_path(@projectName) %>
	<br>
	<br>
	<%= form_tag(first_logout_path :method => "post", :action => "logout", :class => "myLogout") do%>
		<%= submit_tag("Logout") %>
	<% end %>
	<% end %>
	<div class="footer">
		<p>@steffo 2013<p>
	</div>
</div>